name: Python-Script
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4.1.3
      - name: Install Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Flask Script
        run: python3 main.py
